// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjZ1cLo9xZOtyo1a8WTcpTcDcpzFQQhhA',
    appId: '1:964509482228:web:675fa52cd8e98f8a3472a1',
    messagingSenderId: '964509482228',
    projectId: 'diario-compartilhado-4f2b3',
    authDomain: 'diario-compartilhado-4f2b3.firebaseapp.com',
    storageBucket: 'diario-compartilhado-4f2b3.appspot.com',
    measurementId: 'G-GH6NM02XT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsAjM-FBZw62TZfxG-JrjJB82Ku01lbes',
    appId: '1:964509482228:android:c715d9bab4f770b03472a1',
    messagingSenderId: '964509482228',
    projectId: 'diario-compartilhado-4f2b3',
    storageBucket: 'diario-compartilhado-4f2b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9avKtU_SkrfTfhtQWNn01sBujZYW2PYM',
    appId: '1:964509482228:ios:47200307da62ea6f3472a1',
    messagingSenderId: '964509482228',
    projectId: 'diario-compartilhado-4f2b3',
    storageBucket: 'diario-compartilhado-4f2b3.appspot.com',
    iosBundleId: 'com.example.diarioCompartilhado',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9avKtU_SkrfTfhtQWNn01sBujZYW2PYM',
    appId: '1:964509482228:ios:c950b5bfa3bb09913472a1',
    messagingSenderId: '964509482228',
    projectId: 'diario-compartilhado-4f2b3',
    storageBucket: 'diario-compartilhado-4f2b3.appspot.com',
    iosBundleId: 'com.example.diarioCompartilhado.RunnerTests',
  );
}
